name: micro_app_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_route:
  hive:
  hive_flutter:
  url_launcher: ^6.2.5
  micro_core:
    path: ../micro_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  auto_route_generator: ^7.3.2
  

flutter:
  uses-material-design: true

build:
  spa_fallback: true
